# Eat Safe, Love

## Notebook Set Up

In [1]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
print(db.list_collection_names())

['establishments']

In [5]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [19]:
# Find the establishments with a hygiene score of 20
query = {'scores.Hygiene': {'$eq':20}}
# Use count_documents to display the number of documents in the result
print("Establishments with a hygiene score of 20:", establishments.count_documents(query))
# Display the first document in the results using pprint
pprint(establishments.find_one(query))

Establishments with a hygiene score of 20: 41
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('67ddc22d0105d8b28248743a'),
 'geocode': {'latitude': Decimal128('50.769705'),
             'longitude': Decimal128('50.769705')},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [21]:
# Convert the result to a Pandas DataFrame
hygiene_df = pd.json_normalize(list(establishments.find(query)))
# Display the number of rows in the DataFrame
print("Number of rows:", hygiene_df['_id'].count())
# Display the first 10 rows of the DataFrame
hygiene_df.head(10)

Number of rows: 41

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,67ddc22d0105d8b28248743a,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,50.769705,50.769705,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,67ddc22d0105d8b2824877bb,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,51.857536,51.857536,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,67ddc22d0105d8b282487ac7,730933,0,1698/FOOD,Melrose Hotel,Hotel/bed & breakfast/guest house,7842,53 Marine Parade East,Clacton On Sea,Essex,...,51.789429,51.789429,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,67ddc22d0105d8b282487cb6,172735,0,PI/000023858,Seaford Pizza,Takeaway/sandwich shop,7844,4 High Street,Seaford,East Sussex,...,50.770885,50.770885,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,67ddc22d0105d8b282487cc4,172953,0,PI/000024532,Golden Palace,Restaurant/Cafe/Canteen,1,5 South Street,Seaford,East Sussex,...,50.770724,50.770724,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,67ddc22d0105d8b282488663,512854,0,12/00816/BUTH,Ashby's Butchers,Retailers - other,4613,777 Southchurch Road,Southend-On-Sea,Essex,...,51.541448,51.541448,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,67ddc22d0105d8b282488884,1537089,0,22/00224/RESTUN,South Sea Express Cuisine,Restaurant/Cafe/Canteen,1,33 Alexandra Street,Southend-on-sea,Essex,...,51.5350065,51.5350065,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,67ddc22d0105d8b282489daf,155648,0,EH/00006058,Golden Palace,Takeaway/sandwich shop,7844,7 London Road,Rayleigh,Essex,...,51.591515,51.591515,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,67ddc22d0105d8b28248a1fa,1012883,0,17/00110/MIXED/S,The Tulip Tree,Restaurant/Cafe/Canteen,1,3 The Village,Chiddingstone,KENT,...,51.1859474182129,51.1859474182129,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,67ddc22d0105d8b28248aa06,644109,0,41811,F & S,Retailers - other,4613,,81 Southernhay,Basildon,...,51.57005,51.57005,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [22]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {'RatingValue': {'$gte':4}, 'LocalAuthorityName': {'$regex': 'London'}}
# Use count_documents to display the number of documents in the result
print("Establishments in London Local Authority with a Rating greater than or equal to 4:", establishments.count_documents(query))
# Display the first document in the results using pprint
pprint(establishments.find_one(query))

Establishments in London Local Authority with a Rating greater than or equal to 4: 33
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('67ddc22d0105d8b282488e58'),
 'geocode': {'latitude': Decimal128('51.369321'),
             'longitude': Decimal128('51.369321')},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [23]:
# Convert the result to a Pandas DataFrame
london_rating_df = pd.json_normalize(list(establishments.find(query)))
# Display the number of rows in the DataFrame
print("Number of rows:", london_rating_df['_id'].count())
# Display the first 10 rows of the DataFrame
london_rating_df.head(10)

Number of rows: 33

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,67ddc22d0105d8b282488e58,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,51.369321,51.369321,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,67ddc22d0105d8b28248917d,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,51.1236228942871,51.1236228942871,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,67ddc22d0105d8b282489cd1,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,51.543831,51.543831,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,67ddc22d0105d8b28248aac8,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,51.4640655517578,51.4640655517578,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,67ddc22d0105d8b28248aacb,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,51.464078,51.464078,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,67ddc22d0105d8b28248b1d5,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,51.504071,51.504071,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,67ddc22d0105d8b28248d2e0,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,51.501121,51.501121,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,67ddc22d0105d8b28248d6a9,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,51.503733,51.503733,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,67ddc22d0105d8b28248d6c2,294606,0,PI/000016185,WH Smith,Retailers - other,4613,London City Airport,Silvertown London,,...,51.5041122436523,51.5041122436523,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,67ddc22d0105d8b28248d6c3,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,51.504112,51.504112,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [60]:
query_new_restaurant = {'BusinessName': 'Penang Flavours'}
latitude = list(establishments.find_one(query_new_restaurant, {'geocode.latitude': 1}).values())[1]
print(latitude)

{'latitude': Decimal128('51.49014200')}

In [117]:
query_new_restaurant = {'BusinessName': 'Penang Flavours'}
latitude = float(str(list(establishments.find_one(query_new_restaurant, {'geocode.latitude': 1})['geocode'].values())[0]))
latitude

51.490142

In [116]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
query_new_restaurant = {'BusinessName': 'Penang Flavours'}
latitude = float(str(list(establishments.find_one(query_new_restaurant, {'geocode.latitude': 1})['geocode'].values())[0]))
longitude = float(str(list(establishments.find_one(query_new_restaurant, {'geocode.longitude': 1})['geocode'].values())[0]))

query = {'RatingValue': {'$eq':5}, 'geocode:latitude': [{'$gte':latitude-degree_search}, {'$lte':latitude+degree_search}], 'geocode:longitude': [{'$gte':longitude-degree_search}, {'$lte':longitude+degree_search}]}
sort = ['scores.Hygiene']
limit = 5

# Print the results
pprint(list(establishments.find(query).sort(sort).limit(limit)))

[]

In [118]:
degree_search = 0.01
query_new_restaurant = {'BusinessName': 'Penang Flavours'}
latitude = float(str(list(establishments.find_one(query_new_restaurant, {'geocode.latitude': 1})['geocode'].values())[0]))
longitude = float(str(list(establishments.find_one(query_new_restaurant, {'geocode.longitude': 1})['geocode'].values())[0]))

print("Latitude: ", latitude, " / Longitude: ", longitude)

Latitude:  51.490142  / Longitude:  51.490142

In [119]:
degree_search = 0.01
query_new_restaurant = {'BusinessName': 'Penang Flavours'}
establishments.find_one(query_new_restaurant)

{'_id': ObjectId('67ddc243a91eaca5b5096267'),
 'BusinessName': 'Penang Flavours',
 'BusinessType': 'Restaurant/Cafe/Canteen',
 'BusinessTypeID': 1,
 'AddressLine1': 'Penang Flavours',
 'AddressLine2': '146A Plumstead Rd',
 'AddressLine3': 'London',
 'AddressLine4': '',
 'PostCode': 'SE18 7DY',
 'Phone': '',
 'LocalAuthorityCode': '511',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'scores': {'Hygiene': '', 'Structural': '', 'ConfidenceInManagement': ''},
 'SchemeType': 'FHRS',
 'geocode': {'longitude': Decimal128('51.49014200'),
  'latitude': Decimal128('51.49014200')},
 'RightToReply': '',
 'Distance': 4623.972328074718,
 'NewRatingPending': True,
 'RatingValue': None}

In [ ]:
# Convert result to Pandas DataFrame

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [ ]:
# Create a pipeline that:
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest

# Print the number of documents in the result

# Print the first 10 results

In [ ]:
# Convert the result to a Pandas DataFrame

# Display the number of rows in the DataFrame

# Display the first 10 rows of the DataFrame